### ISSUE TITLE
terminal and powerline theme 

### ISSUE THREAD

**Issue by damiponce** [ABSphreak/ABSphreak#6]
hey! I was scrolling through some issues as one does, and [found ](https://github.com/Peltoche/lsd/issues/393#issue-664316183)your terminal screenshot very pleasing. would love to know what powerline theme is that, and what colour theme you use for your terminal/shell. thanks!

**Comment by ABSphreak** [comment]
Hey @damiponce! Thanks for reaching out.

That issue is pretty old, it was WSL inside Windows Terminal.
- Font is [Cascadia Code](https://github.com/microsoft/cascadia-code) from Microsoft.
- Powerline theme is [powerlevel10k](https://github.com/romkatv/powerlevel10k) or [9k](https://github.com/Powerlevel9k/powerlevel9k) on [zsh](https://ohmyz.sh/).
- Color Scheme is Elementary or Ubuntu I believe, check them out [here](https://windowsterminalthemes.dev/).

Hope it helps! ✌️

Would love to know about your setup too!

**Comment by damiponce** [comment]
Thanks! 
I also use Windows Terminal, but for my font choice I always go with Apple's SF Mono. Although not open source, I'm not using it commercially so I don't think it's wrong in any sense 😅

**Comment by ABSphreak** [comment]
Nice! SF Mono is a good font. Do you patch it with Powerline Glyphs using [Nerd Font](https://www.nerdfonts.com/)?

**Comment by damiponce** [comment]
I haven't done that yet with my current setup, I remember patching some other font with it some time ago. Thanks for the reminder!

**Comment by ABSphreak** [comment]
Cool!
